### ISSUE TITLE
Store / Send some no smoke images

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-engine#27]
## 🚀 Feature

Define a strategy to send/store some of the no smoke images (and implement it :))

## Motivation / Pitch
To date, if images associated with a smoke detection are communicated to the api and thus stored, we do not keep any images a priori without smoke. 

However, for various reasons it would be relevant to keep some of them (useful to balance our dataset, to train our model on the specific vegetation of the installed sites, or on a daily basis, to check if the field of view is not obstructed)

Hence, it is needed to define, a frequency,  sampling methodology and decide if those images are send to pyro-api (using media route) or if images are stored on devices.

From @pyronear/vision point of view, for a device, how many no smoke images you would want to store per day/week ?

Do we fix a probability to send a no smoke image (relatively to a device of any img going through the webserver), define a constant rate, or any other strategy ?

Also, which resolution is relevant  ?

As long as we have roots to upload some media, maybe a suitable solution is to send images (instead of storing on SD card and retrieve data when going on sites). If images are stored, need to size SD card properly, but I am not fan of this solution. 
If images are sent, need to ensure the 10go/month of 4G subscription is not reached. 

What do you think ?

Happy to discuss it.

**Comment by blenzi** [comment]
Hi @fe51, thanks for initiating this discussion. I totally agree this is very relevant and #39 is a first step to address this. I also agree the pictures should be transferred and not (only) stored to be collected later.

A rough estimate gives 1 GB / month for a 200 kB picture / camera every 1/2h with 5 cameras per tower x 17h activity / day x 30 days. This is well within our budget.

To check the status of the camera and system, a single image is enough. However, to evaluate the sensitivity of the algorithms and to maximize their performance, one probably needs sequences, including pictures before and after crossing the detection threshold. Does it make sense?

**Comment by frgfm** [comment]
Apart from the telco topic, where I don't have enough experience to help, here is my point of view:
- the API does allow for a device to upload a media (without it being an alert). So the backend is ready on that part
- regarding the distribution selection, this is a very hard question. For a fixed point of view, I'd argue we only need as many pictures as there are different visual situations (time of the day, time of the year, weather). So that means we could be needing 5 images / day from a given site, just like only 1 / month.

To suggest something helpful on that last part, here is a suggestion:
- we can't decide yet (or ever) a fixed rule for this, so let's not decide
- just like we have something in the DB to tell the device to update itself, we could have something to tell them "alright, today is the today, please take 1 picture / hour"

This would imply:
- define the acquisition schemes (frequency, duration of scheme, etc.)
- make the modification in backend (which would be quite easy)
- implement it in pyroengine and/or pyro-sys-setup

**Comment by frgfm** [comment]
Solved by #50
