### ISSUE TITLE
Add package to pypi or fix installation instructions

### ISSUE THREAD

**Issue by blenzi** [pyronear/pyro-engine#38]
## 🚀 Feature

The instructions suggest to install the package directly via pip but it is not in pypi:

```
$ pip install pyroengine

ERROR: Could not find a version that satisfies the requirement pyroengine (from versions: none)
ERROR: No matching distribution found for pyroengine
```

Should it be included or the instructions are to be changed?

**Comment by MateoLostanlen** [comment]
@blenzi The first release will be publish when our v1 is ready, this is why there is no available package on pip

**Comment by frgfm** [comment]
Hello everyone :wave: 

I had to fix a few things which resolve this issue:
- @MateoLostanlen I realized the last tag was incoherent (v0.0.1) compared to the previous one (v0.1.0). So I created a new one with a release (v0.1.1)
- I pushed to pypi the release v0.1.0 and v0.1.1 since they were available up until then. That means that `pip install pyroengine` now works

Now we're on track for v0.2.0 :grin:
