### ISSUE TITLE
[tests] Adds unittests to check API interactions within pyroengine

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-engine#51]
## 🚀 Feature
We have to create a system to test the calls to the api in our tests, this repo is strongly linked to the pyro-api, we can't leave a big part of the code without any test. Maybe we can launch a simplified api locally in the test environment.

@pyronear/back-end Do you have any ideas?

**Comment by frgfm** [comment]
Sorry about the delay!
I can see a few options:
- running the actual API in the CI since the repo provides a functional docker image
- making a custom version of the API for the CI
- not doing anything to reproduce the behaviour in the CI

I suggest the first one which would be the easiest one and the closest to the situation in production

**Comment by MateoLostanlen** [comment]
Ok I will test this, thaks !

**Comment by frgfm** [comment]
Closed by #108
